name: Webpack build and deploy to Github Pages

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm install
          npx webpack
